name: parent_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.3+3

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.7+3
  provider: ^4.0.4
  charts_flutter: ^0.9.0
  http: ^0.12.0+4
  flutter_staggered_grid_view: ^0.3.0
  timeline_list: ^0.0.5
  table_calendar: ^2.2.3
  calendar_strip: ^1.0.6
  google_maps_flutter: ^0.5.25
  location: ^2.3.5
  percent_indicator: ^2.1.1+1
  month_picker_dialog: ^0.3.1
  flutter_timetable_view: ^0.1.0
  razorpay_flutter: ^1.1.1
  fluttertoast: ^4.0.0
  awesome_dialog: ^0.1.3
  dash_chat: ^1.0.18
  image_picker: ^0.6.4
  file_picker: ^1.9.0+1
  sqflite: ^1.3.0
  path: ^1.6.4
  firebase_core: ^0.4.4+3
  firebase_analytics: ^5.0.11
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.1.5
  flutter_swiper: ^1.1.6
  after_layout: ^1.0.7+2
  flutter_rating_bar: ^3.0.1+1
  page_turn: ^1.0.0
  date_picker_timeline: ^1.2.0
  video_player: ^0.10.10
  webview_flutter: ^0.3.21
  nima: ^1.0.5
  syncfusion_flutter_gauges: ^18.1.48
  expandable: ^4.1.4
  agora_rtc_engine: ^1.0.12
  permission_handler: ^5.0.0+hotfix.6
  flutter_youtube: ^2.0.0
  wakelock: ^0.1.4+1
  chewie: ^0.9.10
  flutter_launcher_icons: ^0.7.5
#  youtube_player_flutter: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/menu/
    - assets/images/events/
    - assets/images/scholarships/
    - assets/images/blue_gradient.jpg
    - assets/images/sir.jpg
    - assets/images/diary_header.png
    - assets/images/diary_0.png
    - assets/images/diary_1.png
    - assets/images/menu_0.png
    - assets/images/menu_1.png
    - assets/images/menu_2.png
    - assets/images/menu_3.png
    - assets/images/menu_4.png
    - assets/images/menu_5.png
    - assets/images/menu_6.png
    - assets/images/menu_7.png
    - assets/images/menu_8.png
    - assets/images/menu_9.png
    - assets/images/menu_10.png
    - assets/images/menu_11.png
    - assets/images/menu_12.png
    - assets/images/menu_13.png
    - assets/images/menu_14.png
    - assets/images/schoolbus.png
    - assets/images/1001.jpg
    - assets/images/1002.jpg
    - assets/images/1003.jpg
    - assets/images/school.jpg
    - assets/images/digi_campus_logo.png
    - assets/images/ucevents.png
    - assets/videos/smartschool.mp4
    - assets/sqlite/local_data_parent_app.db
    - assets/animations/superman-podium.nma
    - assets/animations/superman-podium.png
    - assets/images/tutorial0.jpg
    - assets/images/tutorial1.jpg
    - assets/images/tutorial2.jpg
    - assets/images/tutorial3.jpg
    - assets/images/raised_hand.png
    - assets/images/school_logo.jpeg
    - assets/images/school_logo.png
    - assets/images/user.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-bold.ttf

    - family:  MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf

    - family:  RaiseHand
      fonts:
        - asset: assets/fonts/raisehand.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"
  adaptive_icon_background: "assets/images/launcher_bg.png"
  adaptive_icon_foreground: "assets/images/launcher_fg.png"